version: "3.9"
services:
  redis:
    image: redis:7.0.2-alpine
    restart: always
    ports:
      - "6379:6379"
  serial-receiver:
    build:
      context: ./serialReciever
    restart: always
    volumes:
      - /dev:/dev
    env_file:
      - ./serialReciever/serial-receiver.env
    depends_on:
      - "redis"
    privileged: true
  serial-sender:
    build:
      context: ./SerialSender
    restart: always
    volumes:
      - /dev:/dev
    depends_on:
      - "redis"
    privileged: true
  cloud-sender:
    build:
      context: ./cloudSender
    restart: always
    env_file:
      - ./cloudSender/cloud-sender.env
    depends_on:
      - "redis"
  cloud-receiver:
    build:
      context: ./MqttReciever
    restart: always
    env_file:
      - ./MqttReciever/mqtt-receiver.env
    depends_on:
      - "redis"
